[package]
name = "a_sabr_python"
version = "0.1.0"
edition = "2021"

[lib]
name = "a_sabr_python"
crate-type = ["cdylib"]

[dependencies]
a_sabr = { git = "https://github.com/DTN-MTP/a-sabr", branch = "main"}
pyo3 = { version = "0.24.1", features = ["extension-module"] }
serde_json = "1.0"

[features]
default = ["a_sabr/default"]
debug = ["a_sabr/debug"]
contact_suppression = ["a_sabr/contact_suppression"]
first_depleted = ["a_sabr/first_depleted"]
manual_queueing = ["a_sabr/manual_queueing"]
